version: '3.8'
services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  voicevox:
    image: voicevox/voicevox_engine:cpu-latest
    ports:
      - "50021:50021"
    healthcheck:
      test: ["CMD", "/opt/python/bin/python3", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:50021/version', timeout=10)"]
      interval: 90s
      timeout: 30s
      retries: 3
      start_period: 180s
    restart: unless-stopped
    environment:
      - VOICEVOX_CORE_VERSION=0.14.4
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  yousaysan:
    build:
      context: ./
      target: production
    depends_on:
      voicevox:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "pgrep", "-f", "ruby.*run.rb"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"