services:
  yousaysan:
    build:
      context: ..
      dockerfile: Dockerfile
      target: development
    volumes:
      - ..:/app:cached
      - go-mod-cache:/go/pkg/mod
      - go-build-cache:/go/cache
    command: bash -lc "sleep infinity"
    environment:
      - VOICEVOX_HOST=http://voicevox:50021
      - REDIS_HOST=redis
    depends_on:
      - voicevox
      - redis
  voicevox:
    image: voicevox/voicevox_engine:cpu-latest
  redis:
    image: redis:7-alpine
volumes:
  go-mod-cache:
  go-build-cache:
